### PR TITLE
update support-i18n to release with scala 2.13 and 3.1

### PR DESCRIPTION
**Pull request by johnduffell**
This PR updates support-i18n to release for scala 2.13 and 3.1., and releases v0.14

It didn't even build with scala 2.11, and it had previously been released for scala 2.13 (for support-service-lambdas)

We now use scala 3 for new product-move-api, and even though scala 3 can use scala 2.13 libraries, it does make sense to release scala 3 libs where possible.

I have done a release to confirm my changes work, so this PR is to review what's already been done!  Release is visisble here https://mvnrepository.com/artifact/com.gu/support-internationalisation_3/0.14

---

I did have a go at making it a scala 3 only module (see https://github.com/guardian/support-frontend/compare/jd-support-i18n-scala-3...jd-support-i18n-scala-3-only ), but there seems to be an issue with scalatest versions that stops the tests from compiling as follows:
```
[IJ]support-workers/Test/compile
[info] compiling 43 Scala sources and 1 Java source to /Users/john_duffell/code/support-frontend/support-workers/target/scala-2.13/test-classes ...
[error] Unsupported Scala 3 generic tuple type scala.Tuple in bounds of type MirroredElemTypes; found in  scala.deriving.Mirror.<refinement>.
[error] one error found
[error] (Test / compileIncremental) Compilation failed
[error] Total time: 18 s, completed 16-Aug-2022 10:26:45
```

### CODE REVIEW

File: support-internationalisation/src/test/scala/com/gu/i18n/CountryGroupTest.scala [hunk 1]
```diff
@@ -1,11 +1,11 @@
...
 
 import com.gu.i18n.Currency._
-import org.scalatest.Inspectors
-import org.scalatest.flatspec.AsyncFlatSpec
+import org.scalatest._
+import org.scalatest.flatspec.AnyFlatSpec
 import org.scalatest.matchers.should.Matchers
 
-class CountryGroupTest extends AsyncFlatSpec with Matchers with Inspectors {
+class CountryGroupTest extends AnyFlatSpec with Matchers with Inspectors {
```
Comment (johnduffell) [inline support-internationalisation/src/test/scala/com/gu/i18n/CountryGroupTest.scala:8]: scala 3 scalatest noticed that these weren't actually async tests, somehow scala 2 one didn't.

**Comment by johnduffell** [comment]
replaced by https://github.com/guardian/support-frontend/pull/4136

**Comment by johnduffell** [comment]
it turned out it was a scala <= 2.13.8 compatibliity with scala >=3.1.3 issue stopping things compiling.

By downgrading the scala version slightly, everything seems to compile ok.  See https://github.com/lampepfl/dotty/issues/15878
